version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["5432:5432"]
    volumes: [db_data:/var/lib/postgresql/data]
    networks:
      - todo_network

  api:
    build: ./apps/api
    env_file: .env
    depends_on: [db]
    ports: ["4000:4000"]
    command: sh -c "npx prisma migrate deploy && node dist/server.js"

  web:
    build: ./apps/web
    env_file: .env
    depends_on: [api]
    ports: ["3000:3000"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: todo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - todo_network

  # OPTIONAL reverse proxy in front of both (see nginx.conf below)
  nginx:
    image: nginx:alpine
    volumes:
      - ./apps/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: [web, api]
    ports: ["80:80"]

volumes:
  db_data: {}

networks:
  todo_network:
